### ISSUE TITLE
LineAgeOS 15.1 compatibility

### ISSUE THREAD

**Issue by ghost** [saiho/ToggleLineageProfiles#1]
It seems, that your app isn't working on LenAgeOS 15.1 based roms. When I open the app, there's only the message that LinaAgeOS wasn't detected.

I'm using Resurrection Remix, which is based on LineAgeOS 15.1/Android 8.1.

I hope you can help. If you need further information, just tell me.

_Gesendet von meinem One mit [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by saiho** [comment]
Hello, thanks for your comment. The SDK library has changed in LineageOS 15.1, that's the reason that it is not detected with the old one. I don't have a device running 15.1 now, but I could try adding the code to use the new library and hope it works for you.

I'll keep you informed about any progress.

**Comment by saiho** [comment]
I have just added support for LineageOS 15, but I've not been able to test it. Your feedback is appreciated.
