### ISSUE TITLE
Feature request: tile in quicksettings

### ISSUE THREAD

**Issue by ghost** [saiho/ToggleLineageProfiles#2]
And a feature request: a tile in the quicksettings to switch profiles would be great. That's the main reason, why I tested your app.

Anyway, thanks for being an open source developer.

_Gesendet von meinem One mit [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by saiho** [comment]
Hello, could you describe with more detail this feature? As right now, Lineage OS 14.1 has the option to add a button to change the profile from the quick settings (dragging down from the notification bar). That's a built-in functionality, so I guess you are referring to something different.

**Comment by ghost** [comment]
I 'regfering to the same. But on LineageOS 15+ they removed the tile again. 

_Gesendet von meinem One mit [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by saiho** [comment]
In that case I'll think in adding the tile to the quick settings in a future release.

**Comment by saiho** [comment]
Current builds of LOS 15 already have this feature, so no need to add it to this app.

**Comment by flortsch** [comment]
I am running LOS16 and it seems that they again removed the tile in the quick settings. So maybe this feature request might become important again.

**Comment by saiho** [comment]
Thanks for the information,

I will reopen, although not sure when will be possible to do it.

**Comment by saiho** [comment]
Added functionality for quick settings.
