### ISSUE TITLE
Doesn't Work in LineageOS 18.0

### ISSUE THREAD

**Issue by landry314** [saiho/ToggleLineageProfiles#3]
It crashes upon opening and widgets load perpetually. Unusable in LineageOS 18...

**Comment by landry314** [comment]
i tried allowing system modifications too... nothing. i'd love to get this to work!

**Comment by saiho** [comment]
Hello,

Thanks for the information.

LineageOS 18 is quite new and I don't have a phone running this version. I'll try to check with an emulator.

**Comment by landry314** [comment]
maybe compiling with updated dependencies would fix it. i could test the new build.

**Comment by landry314** [comment]
These links might be interesting related to this issue:

https://www.reddit.com/r/tasker/comments/f4v0l0/how_to_switching_lineageos_profiles_and_possibly/

https://gist.github.com/udf/96272b281315c492e2df4998bc6979a4

**Comment by saiho** [comment]
I've made a new build using the SDK of Lineage 17.1. Hopefully this will work also with Lineage 18. Could you try?

Thanks a lot.

**Comment by landry314** [comment]
IT WORKS!

**Comment by landry314** [comment]
IT WORKS! I tried every feature including the quick tiles and it all works in LOS 18.1 for Pixel 3!

**Comment by landry314** [comment]
The only problem is the widget icon is not aligned with the other icons on the grid for the launcher. The icon is lower and the text size and color don't conform. It's weird.

**Comment by saiho** [comment]
Good to know. Could you send me an screenshot?
