### ISSUE TITLE
Widget Icon Not Conformed With Other Icons In Launcher

### ISSUE THREAD

**Issue by landry314** [saiho/ToggleLineageProfiles#5]
Continuing from issue #3, the widget icon is not aligned with the other icons on the grid in the launcher. The icon is lower and the text size and color don't conform. Screenshot attached.

I am using Nova Launcher in LOS 18.1 on a Pixel 3.

It is great that we can select colors for the icon but I'd like the text for the name of the app to conform to the launcher default.

Maybe the setting that allows you to change the size of the text can be off by default. The widget should conform with the rest of the launcher normally.

![Screenshot_20210121-234514_Nova_Launcher](https://user-images.githubusercontent.com/6866501/105427292-cc371880-5c1a-11eb-9209-b366fb5d742b.png)

**Comment by saiho** [comment]
I see. The problem in fact is that every launcher uses its own layout. For instance I see other differences using the AOSP launcher. The app itself cannot detect what's the layout of the launcher, and also some launchers add an extra margin that cannot be removed and makes everything smaller (hopefully, that's not the case of Nova). The only thing I can do is add more configuration settings to allow fine adjustment of the margins and size the icon and text.

**Comment by landry314** [comment]
the widget cant just NOT customize itself UNLESS the user turns it on?

**Comment by saiho** [comment]
That's right. There is no way (that I know) to configure the aspect automatically to match everyone's launcher.
The adjustment should be done manually. Of course, still I have to add such new settings to the app for that...

**Comment by saiho** [comment]
I have uploaded a new version with new settings that allow controlling the margins of the widget. Increasing the margins will reduce the size of the icon. You can also play with the top, middle and bottom margins to align the widget's icon and the text with the rest of the icons on the screen.

I know it is not a very intuitive and quick way to change the appearance, but it should at least be flexible enough to allow everyone to adjust depending on their needs.
