### ISSUE TITLE
Add Tasker Plugin Integration

### ISSUE THREAD

**Issue by bbbco** [saiho/ToggleLineageProfiles#7]
You should add Tasker Plugin Integration so that we can automate the switching of profiles. This would be similar to the Profile Shortcuts for Lineage OS app that did this for LineageOS up through 16. That is the app I used to use for automation until I upgraded to LOS 17.1, and the app is broken. I'd love to replace this functionality with your awesome app, but still need that Tasker integration pretty please! :)

**Comment by landry314** [comment]
so interesting i just opened issue #6 that also requires this tasker functionality and refers to the same deprecated app!

**Comment by saiho** [comment]
Included Blacky-Toggle changes in latest version, I hope it allows now to change profiles from Tasker.

**Comment by Ra72xx** [comment]
> Included Blacky-Toggle changes in latest version, I hope it allows now to change profiles from Tasker.

Could you give an example how to use this from Tasker (screenshot or so)? The pull request contains a few text lines, but I don't really get it how to implement this in Tasker's GUI.

**Comment by harphere** [comment]
> > Included Blacky-Toggle changes in latest version, I hope it allows now to change profiles from Tasker.
> 
> Could you give an example how to use this from Tasker (screenshot or so)? The pull request contains a few text lines, but I don't really get it how to implement this in Tasker's GUI.

@Larx, it's supposed to be run as an Intent but I haven't had any success so far. See [here](https://github.com/saiho/ToggleLineageProfiles/pull/11#issue-1326426757)  for the task; maybe you can figure it out.
