### ISSUE TITLE
Display Settings Keep Reverting To Defaults

### ISSUE THREAD

**Issue by landry314** [saiho/ToggleLineageProfiles#8]
No matter how I adjust the icon display, it keeps reverting back to defaults when I reboot the phone.

LOS 18.1, Pixel 3.

**Comment by saiho** [comment]
I tried to reproduce the issue, but for me the settings are maintained after restarting the phone. I used latest version of LOS 18.1 built for emulator.

I suppose you tried to uninstall and reinstall the app?

**Comment by landry314** [comment]
I uninstalled and reinstalled then changed settings and restarted and it has kept the settings so far... i'll post if it forgets again.

**Comment by landry314** [comment]
Ok, it is working fine now...
